name: build

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-24.04

    permissions: write-all

    services:
      backend:
        image: ghcr.io/muchobien/pocketbase:latest
        ports:
          - "8090:8090"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure pocketbase
        run: |
          docker exec ${{ job.services.backend.id }} \
          sh -c 'pocketbase superuser create yo@soypache.co Password.123'

      - uses: tacoss/nodejs@master
        with:
          args: make dist smoke test-nodejs coverage
        env:
          PB_ADMIN_URL: http://backend:8090
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Deno setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.5.4

      - run: make test-deno

      - name: Bun setup
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 1.3.6

      - run: make test-bun
