name: build

on:
  push:
    branches:
    - next
  pull_request:
    branches:
    - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd "pg_isready -U postgres -d postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      backend:
        image: ghcr.io/muchobien/pocketbase:latest
        ports:
          - "8090:8090"

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 23.1.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deno setup
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.0.4
      - name: Bun setup
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 1.1.34

      - name: Configure pocketbase
        run: |
          docker exec ${{ job.services.backend.id }} sh -c 'pocketbase admin create yo@soypache.co Password.123'

      - name: Run all tests
        run: make ci DIST_TASK=dist:min CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
